[build]
  # Directory to publish (relative to root of your repo)
  publish = "public"
  
  # Default build command (not needed for static sites, but good to have)
  command = "echo 'No build step required for static site'"

[build.environment]
  # Node.js version (if needed for any build tools)
  NODE_VERSION = "18"

# Redirect rules
[[redirects]]
  # Redirect root to index.html (for SPA-like behavior)
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    # Security headers
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # Cache control for static assets
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.html"
  [headers.values]
    # Different cache control for HTML files
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/*.png"
  [headers.values]
    # Optimize image caching
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.jpeg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.gif"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Form handling (if you add forms later)
# [build.processing]
#   skip_processing = false
# [build.processing.css]
#   bundle = true
#   minify = true
# [build.processing.js]
#   bundle = true
#   minify = true
# [build.processing.html]
#   pretty_urls = true
